#!/bin/bash -x 
#SBATCH --job-name=Pre_ur
#SBATCH --account=kgidiotis
#SBATCH --cpus-per-task=6
#SBATCH --mem=10G
#SBATCH --partition=fatnodes 
#SBATCH --output=/projects/125-emmer/free_threshing/fastqs_Zhou2020/errors/prefast_%j.out
#SBATCH --error=/projects/125-emmer/free_threshing/fastqs_Zhou2020/errors/prefast_%j.err


#module load conda
#conda activate my_env

output_directory=/projects/125-emmer/free_threshing/fastqs_Zhou2020
#list=/home/kgidiotis/scripts/SRR_Acc_List.txt
path=/projects/125-emmer/kostas/sratoolkit.3.1.0-ubuntu64/bin
#output=/scratch/125-emmer/kostas/data/triticum_paleocolchicum

# this is to run specific SRAs
#python Prefast.py

#echo "Runs the prefetch"
# this extracts a list of SRAs (text format) and runs them all 
#${path}/prefetch -O $output_directory --option-file $list

echo "Runs the fastq-dump"
# Iterate over .sra files and run fasterq-dump
find "$output_directory/triticum_urartu" -type f -name "*.sra" | while read -r file; do
    echo "${file}"
    bsub ${path}/fastq-dump --outdir $output_directory/triticum_urartu --split-3 --gzip "$file"
done

#find $output_directory -name "*.sra" -exec bsub ${path}/fasterq-dump --split-3 --gzip {} \;

#conda deactivate
