#!/bin/bash -x 
#SBATCH --job-name=gfapy
#SBATCH --partition=general
#SBATCH --nodes=1
#SBATCH --cpus-per-task=5
#SBATCH --mem=10G
#SBATCH --output=/home/kgidiotis/scripts/errors/gfapy_%j.out
#SBATCH --error=/home/kgidiotis/scripts/errors/gfapy_%j.err
# Author: Konstantinos Gidiotis 

module load conda

conda init bash

conda activate my_env

python plot_pangenomes_using_gfapy.py

conda deactivate


~                                                                                                                                                                                                                                             
~                                                                                                                                                                                                                                             
~                                                                                                                                                                                                                                             
~                                                                                                                                                                                                                                             
~                                                                                                                                                                                                                                             
~                                                                                                                                                                                                                                             
~                                                                                                                                                                                                                                             
~                                                                                                                                                                                                                                             
~                                                                                                                                                                                                                                             
~                                                                                                                                                                                                                                             
~                                                                                                                                                                                                                                             
~                                                                                                                                                                                                                                             
~                        
